<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->name }}</title>
    <style>
        @page { size: A4 landscape; margin: 20mm 25mm; }
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { font-size: 20px; margin-bottom: 4px; color: #1a1a2e; }
        .header p { font-size: 12px; color: #6c757d; margin: 2px 0; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 20px; }
        .summary-card { border: 1px solid #e9ecef; border-radius: 8px; padding: 10px 14px; flex: 1 1 22%; min-width: 150px; }
        .summary-card .label { font-size: 10px; color: #6c757d; text-transform: uppercase; }
        .summary-card .value { font-size: 16px; font-weight: bold; color: #1a1a2e; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background: #f8f9fa; text-align: left; padding: 8px 10px; font-size: 10px; text-transform: uppercase; color: #6c757d; border-bottom: 2px solid #e9ecef; }
        td { padding: 7px 10px; border-bottom: 1px solid #e9ecef; font-size: 12px; }
        .income { color: #28a745; font-weight: 600; }
        .expense { color: #dc3545; font-weight: 600; }
        .amount { text-align: right; font-family: monospace; }
        .footer { margin-top: 20px; font-size: 10px; color: #adb5bd; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report->name }}</h1>
        <p>Type: {{ $typeLabel }} · Period: {{ \Carbon\Carbon::parse($report->date_start)->format('d M Y') }} → {{ \Carbon\Carbon::parse($report->date_end)->format('d M Y') }}</p>
        <p>Aggregation: {{ $aggregationLabel }} · Generated: {{ $report->created_at->format('d F Y, H:i') }}</p>
    </div>

    @if(!empty($summary))
        <div class="summary-grid">
            @foreach($summary as $label => $value)
                <div class="summary-card">
                    <div class="label">{{ $label }}</div>
                    <div class="value">{{ $value }}</div>
                </div>
            @endforeach
        </div>
    @endif

    @if(!empty($rows))
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Type</th>
                    <th class="amount">Amount</th>
                    @if(isset($rows[0]['running_total']))
                        <th class="amount">Running Total</th>
                    @endif
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $row)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($row['date'])->format('d M Y') }}</td>
                        <td>{{ $row['category'] ?? '-' }}</td>
                        <td class="{{ strtolower($row['type'] ?? '') === 'income' ? 'income' : 'expense' }}">
                            {{ $row['type'] ?? '-' }}
                        </td>
                        <td class="amount">
                            Rp {{ number_format((float)($row['amount'] ?? 0), 0, ',', '.') }}
                        </td>
                        @if(isset($row['running_total']))
                            <td class="amount">
                                Rp {{ number_format((float)$row['running_total'], 0, ',', '.') }}
                            </td>
                        @endif
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        W9 Cafe — Financial Report · Generated by {{ $report->user?->name ?? 'System' }} on {{ now()->format('d F Y H:i') }}
    </div>
</body>
</html>
